Processor SDK 12_00_00_01 CICD Release

diff --git a/c7x-mma-tidl/arm-tidl/makefile b/c7x-mma-tidl/arm-tidl/makefile
--- a/c7x-mma-tidl/arm-tidl/makefile
+++ b/c7x-mma-tidl/arm-tidl/makefile
@@ -63,6 +63,11 @@ ifeq ($(shell uname), Linux)
 	MAKE = make
 endif
 
+ALGBASE_PATH      ?= $(abspath ./)
+PSDK_INSTALL_PATH ?= $(abspath ../../)
+PSDK_BUILDER_PATH ?= $(PSDK_INSTALL_PATH)/sdk_builder
+include $(ALGBASE_PATH)/config.mk
+
 all: rt tfl_delegate onnxrt_ep tidlrt_ep
 
 rt:
@@ -126,26 +131,76 @@ tidlrt_ep_scrub:
 	@echo ======== Scrubbing TIDL RT EP  =================
 	rm -rf ./tidlrt_ep/out ./tidlrt_ep/lib
 
-tidl_tiovx_kernels:
+tidl_tiovx_arm_kernels:
 	@echo .
-	@echo ======== MAKING TIDL TIOVX KERNELS =================
+	@echo ======== MAKING TIDL TIOVX ARM KERNELS =================
 	$(MAKE) -C ./tiovx_kernels -f makefile all
 
-tidl_tiovx_kernels_clean:
+tidl_tiovx_arm_kernels_clean:
 	@echo .
-	@echo ======== CLEANING TIDL TIOVX KERNELS =================
+	@echo ======== CLEANING TIDL TIOVX ARM KERNELS =================
 	$(MAKE) -C ./tiovx_kernels -f makefile clean
 
-tidl_tiovx_kernels_scrub:
+tidl_tiovx_arm_kernels_scrub:
 	@echo .
-	@echo ======== SCRUBBING TIDL TIOVX KERNELS  =================
+	@echo ======== SCRUBBING TIDL TIOVX ARM KERNELS  =================
 	rm -rf ./tiovx_kernels/out ./tiovx_kernels/lib
 
+tidl_tiovx_arm_kernels_install:
+ifndef TIDL_PATH
+	$(error TIDL_PATH is not defined. Please set TIDL_PATH before running install)
+else
+	@echo "Installing TIDL TIOVX ARM KERNELS to $(TIDL_PATH)..."
+	@if [ -d "$(TIDL_PATH)" ]; then \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tiovx_kernels/lib/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tiovx_kernels/out/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tiovx_kernels/include/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tiovx_kernels/tidl/include/; \
+		cp -rfL ./tiovx_kernels/lib/* $(TIDL_PATH)/arm-tidl/tiovx_kernels/lib/ 2>/dev/null || :; \
+		cp -rfL ./tiovx_kernels/out/* $(TIDL_PATH)/arm-tidl/tiovx_kernels/out/ 2>/dev/null || :; \
+		cp -rfL ./tiovx_kernels/include/* $(TIDL_PATH)/arm-tidl/tiovx_kernels/include/ 2>/dev/null || :; \
+		cp -rfL ./tiovx_kernels/tidl/include/* $(TIDL_PATH)/arm-tidl/tiovx_kernels/tidl/include/ 2>/dev/null || :; \
+		echo "TIDL TIOVX ARM KERNELS installation complete"; \
+	else \
+		echo "Error: TIDL_PATH '$(TIDL_PATH)' does not exist. Please provide a valid directory path."; \
+		exit 1; \
+	fi
+endif
 
-scrub: rt_scrub tfl_delegate_scrub onnxrt_ep_scrub tidlrt_ep_scrub tidl_tiovx_kernels_scrub
+install: tidl_tiovx_arm_kernels_install
+ifndef TIDL_PATH
+	$(error TIDL_PATH is not defined. Please set TIDL_PATH before running install)
+else
+	@echo "Installing to $(TIDL_PATH)..."
+	@if [ -d "$(TIDL_PATH)" ]; then \
+		mkdir -p $(TIDL_PATH)/arm-tidl/rt/inc/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/rt/lib/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/rt/out/; \
+		cp -rfL ./rt/inc/* $(TIDL_PATH)/arm-tidl/rt/inc/ 2>/dev/null || :; \
+		cp -rfL ./rt/lib/* $(TIDL_PATH)/arm-tidl/rt/lib/ 2>/dev/null || :; \
+		cp -rfL ./rt/out/* $(TIDL_PATH)/arm-tidl/rt/out/ 2>/dev/null || :; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/onnxrt_ep/lib/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/onnxrt_ep/out/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tidlrt_ep/lib/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tidlrt_ep/out/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tfl_delegate/lib/; \
+		mkdir -p $(TIDL_PATH)/arm-tidl/tfl_delegate/out/; \
+		cp -rfL ./onnxrt_ep/lib/* $(TIDL_PATH)/arm-tidl/onnxrt_ep/lib/ 2>/dev/null || :; \
+		cp -rfL ./onnxrt_ep/out/* $(TIDL_PATH)/arm-tidl/onnxrt_ep/out/ 2>/dev/null || :; \
+		cp -rfL ./tidlrt_ep/lib/* $(TIDL_PATH)/arm-tidl/tidlrt_ep/lib/ 2>/dev/null || :; \
+		cp -rfL ./tidlrt_ep/out/* $(TIDL_PATH)/arm-tidl/tidlrt_ep/out/ 2>/dev/null || :; \
+		cp -rfL ./tfl_delegate/lib/* $(TIDL_PATH)/arm-tidl/tfl_delegate/lib/ 2>/dev/null || :; \
+		cp -rfL ./tfl_delegate/out/* $(TIDL_PATH)/arm-tidl/tfl_delegate/out/ 2>/dev/null || :; \
+		echo "Installation complete"; \
+	else \
+		echo "Error: TIDL_PATH '$(TIDL_PATH)' does not exist. Please provide a valid directory path."; \
+		exit 1; \
+	fi
+endif
 
+scrub: rt_scrub tfl_delegate_scrub onnxrt_ep_scrub tidlrt_ep_scrub tidl_tiovx_arm_kernels_scrub
 
 .IGNORE: clean
-clean: rt_clean tfl_delegate_clean onnxrt_ep_clean tidlrt_ep_clean tidl_tiovx_kernels_clean
+clean: rt_clean tfl_delegate_clean onnxrt_ep_clean tidlrt_ep_clean tidl_tiovx_arm_kernels_clean
 
-.PHONY: rt tfl_delegate onnxrt_ep tidlrt_ep tidl_tiovx_kernels rt_clean tfl_delegate_clean onnxrt_ep_clean tidlrt_ep_clean tidl_tiovx_kernels_clean
+.PHONY: rt tfl_delegate onnxrt_ep tidlrt_ep tidl_tiovx_arm_kernels rt_clean tfl_delegate_clean onnxrt_ep_clean tidlrt_ep_clean tidl_tiovx_arm_kernels_clean tidl_tiovx_arm_kernels_install install
diff --git a/c7x-mma-tidl/makefile b/c7x-mma-tidl/makefile
--- a/c7x-mma-tidl/makefile
+++ b/c7x-mma-tidl/makefile
@@ -64,8 +64,11 @@ TIDL_BUILD_ONNX_IMPORT_LIB ?= 1
 
 ALGBASE_PATH ?= $(abspath ./)
 PSDK_INSTALL_PATH ?= $(abspath ../)
+TIDL_PATH ?=$(abspath ./)
 
 include $(ALGBASE_PATH)/makerules/config.mk
+
+$(info ======== CHECKING FOR DEPENDENT MAKEFILES ========)
 
 ifdef SystemRoot
 	MAKE = gmake
@@ -88,50 +91,80 @@ endif
 
 ifneq ("$(wildcard ./ti_dl/algo/makefile)","")
     TIDL_ALGO_FILE_EXISTS = 1
+    $(info [CHECK] ./ti_dl/algo/makefile - FOUND)
 else
     TIDL_ALGO_FILE_EXISTS = 0
+    $(info [CHECK] ./ti_dl/algo/makefile - NOT FOUND)
 endif
 
-ifneq ("$(wildcard ./ti_dl/algo/src/priv/makefile)","")
-    TIDL_PRIV_ALGO_FILE_EXISTS = 1
+ifneq ("$(wildcard ./tidl_priv/source/makefile)","")
+    TIDL_PRIV_FILE_EXISTS = 1
+    $(info [CHECK] ./tidl_priv/source/makefile - FOUND)
 else
-    TIDL_PRIV_ALGO_FILE_EXISTS = 0
+    TIDL_PRIV_FILE_EXISTS = 0
+    $(info [CHECK] ./tidl_priv/source/makefile - NOT FOUND)
 endif
 
-ifneq ("$(wildcard ./ti_dl/algo/src/makefile)","")
-    TIDL_OBJ_ALGO_FILE_EXISTS = 1
+ifneq ("$(wildcard ./tidl_ref/source/makefile)","")
+    TIDL_REF_FILE_EXISTS = 1
+    $(info [CHECK] ./tidl_ref/source/makefile - FOUND)
 else
-    TIDL_OBJ_ALGO_FILE_EXISTS = 0
+    TIDL_REF_FILE_EXISTS = 0
+    $(info [CHECK] ./tidl_ref/source/makefile - NOT FOUND)
+endif
+
+ifneq ("$(wildcard ./tidl_ref/source/avx/makefile)","")
+    TIDL_REF_AVX_FILE_EXISTS = 1
+    $(info [CHECK] ./tidl_ref/source/avx/makefile - FOUND)
+else
+    TIDL_REF_AVX_FILE_EXISTS = 0
+    $(info [CHECK] ./tidl_ref/source/avx/makefile - NOT FOUND)
+endif
+
+ifneq ("$(wildcard ./tidl-kernels/build_all.sh)","")
+    TIDL_KERNELS_FILE_EXISTS = 1
+    $(info [CHECK] ./tidl-kernels/build_all.sh - FOUND)
+else
+    TIDL_KERNELS_FILE_EXISTS = 0
+    $(info [CHECK] ./tidl-kernels/build_all.sh - NOT FOUND)
 endif
 
 ifneq ("$(wildcard ./ti_dl/utils/perfsim/makefile)","")
-    TIDL_NC_FILE_EXISTS = 1
+    TIDL_PERFSIM_FILE_EXISTS = 1
+    $(info [CHECK] ./ti_dl/utils/perfsim/makefile - FOUND)
 else
-    TIDL_NC_FILE_EXISTS = 0
+    TIDL_PERFSIM_FILE_EXISTS = 0
+    $(info [CHECK] ./ti_dl/utils/perfsim/makefile - NOT FOUND)
 endif
 
 ifneq ("$(wildcard ./ti_dl/utils/tidlModelSecure/makefile)","")
     TIDL_MS_FILE_EXISTS = 1
+    $(info [CHECK] ./ti_dl/utils/tidlModelSecure/makefile - FOUND)
 else
     TIDL_MS_FILE_EXISTS = 0
+    $(info [CHECK] ./ti_dl/utils/tidlModelSecure/makefile - NOT FOUND)
 endif
 
 ifneq ("$(wildcard ./ti_dl/utils/tidlModelGraphviz/makefile_runtimes)","")
     TIDL_GV_RT_FILES_EXIST = 1
+    $(info [CHECK] ./ti_dl/utils/tidlModelGraphviz/makefile_runtimes - FOUND)
 else
     TIDL_GV_RT_FILES_EXIST = 0
+    $(info [CHECK] ./ti_dl/utils/tidlModelGraphviz/makefile_runtimes - NOT FOUND)
 endif
+
+$(info ======== MAKEFILE CHECKS COMPLETE ========)
 
 #$(info TIDL_ALGO_FILE_EXISTS $(TIDL_ALGO_FILE_EXISTS))
-#$(info TIDL_NC_FILE_EXISTS $(TIDL_NC_FILE_EXISTS))
-
+#$(info TIDL_PERFSIM_FILE_EXISTS $(TIDL_PERFSIM_FILE_EXISTS))
 
 ifdef SystemRoot
-all: protos nc it tidl dt ms
+all_targets: protos nc it tidl dt ms
 else
-#Conditionally handle for rt
-all: protos nc it tidl dt ms gv gv_rt
+all_targets: protos nc it tidl dt ms gv gv_rt
 endif
+
+all: all_targets
 
 tidl_cuda:
 	@echo .
@@ -140,15 +173,21 @@ ifeq ($(TIDL_ALGO_FILE_EXISTS) , 1)
 	$(MAKE) -C ./ti_dl/algo -f makefile
 	$(MAKE) -C ./ti_dl/custom -f makefile
 endif
-ifeq ($(TIDL_PRIV_ALGO_FILE_EXISTS) , 1)
+ifeq ($(TIDL_REF_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL PRIV ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src/priv -f makefile
+	@echo ======== MAKING TIDL REF =================
+	$(MAKE) -C ./tidl_ref/source -f makefile
 endif
-ifeq ($(TIDL_OBJ_ALGO_FILE_EXISTS) , 1)
+ifeq ($(TIDL_PRIV_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL OBJ ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src -f makefile
+	@echo ======== MAKING TIDL PRIV =================
+	$(MAKE) -C ./tidl_priv/source -f makefile
+endif
+ifeq ($(TIDL_KERNELS_FILE_EXISTS) , 1)
+	@echo .
+	@echo ======== MAKING TIDL KERNELS =================
+	cmake -B ./tidl-kernels/build ./tidl-kernels
+	$(MAKE) -C ./tidl-kernels/build -f Makefile tidl-kernels
 endif
 #	@echo .
 #	@echo ======== MAKING TIDL TEST =================
@@ -161,15 +200,21 @@ ifeq ($(TIDL_ALGO_FILE_EXISTS) , 1)
 	$(MAKE) -C ./ti_dl/algo -f makefile clean
 	$(MAKE) -C ./ti_dl/custom -f makefile clean
 endif
-ifeq ($(TIDL_PRIV_ALGO_FILE_EXISTS) , 1)
+ifeq ($(TIDL_REF_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL PRIV ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src/priv -f makefile clean
+	@echo ======== CLEANING TIDL REF =================
+	$(MAKE) -C ./tidl_ref/source -f makefile clean
 endif
-ifeq ($(TIDL_OBJ_ALGO_FILE_EXISTS) , 1)
+ifeq ($(TIDL_PRIV_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL OBJ ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src -f makefile clean
+	@echo ======== CLEANING TIDL PRIV =================
+	$(MAKE) -C ./tidl_priv/source -f makefile clean
+endif
+ifeq ($(TIDL_KERNELS_FILE_EXISTS) , 1)
+	@echo .
+	@echo ======== CLEANING TIDL KERNELS =================
+	$(MAKE) -C ./tidl-kernels/build -f Makefile clean
+	rm -rf ./tidl-kernels/build
 endif
 #	@echo .
 #	@echo ======== CLEANING TIDL TEST =================
@@ -179,62 +224,110 @@ tidl_algo:
 ifeq ($(TIDL_ALGO_FILE_EXISTS) , 1)
 	@echo ======== MAKING TIDL ALGO =================
 	$(MAKE) -C ./ti_dl/algo -f makefile
-ifeq ($(TARGET_PLATFORM), PC)
-	$(MAKE) -C ./ti_dl/algo/src/avx -f makefile
-endif
 endif
 
 tidl_algo_clean:
 ifeq ($(TIDL_ALGO_FILE_EXISTS) , 1)
 	@echo ======== MAKING TIDL ALGO =================
 	$(MAKE) -C ./ti_dl/algo -f makefile clean
-ifeq ($(TARGET_PLATFORM), PC)
-	$(MAKE) -C ./ti_dl/algo/src/avx -f makefile clean
-endif
 endif
 
 tidl_priv:
-ifeq ($(TIDL_PRIV_ALGO_FILE_EXISTS) , 1)
+ifeq ($(TIDL_PRIV_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL PRIV ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src/priv -f makefile
+	@echo ======== MAKING TIDL PRIV =================
+	$(MAKE) -C ./tidl_priv/source -f makefile
 endif
 
 tidl_priv_clean:
-ifeq ($(TIDL_PRIV_ALGO_FILE_EXISTS) , 1)
-	@echo .
-	@echo ======== MAKING TIDL PRIV ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src/priv -f makefile clean
+ifeq ($(TIDL_PRIV_FILE_EXISTS) , 1)
+	@echo PRIV=YES!
+	@echo ======== CLEANING TIDL PRIV =================
+	$(MAKE) -C ./tidl_priv/source -f makefile clean
 endif
 
-tidl_obj:
-ifeq ($(TIDL_OBJ_ALGO_FILE_EXISTS) , 1)
+tidl_ref:
+ifeq ($(TIDL_REF_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL OBJ ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src -f makefile
+	@echo ======== MAKING TIDL REF =================
+	$(MAKE) -C ./tidl_ref/source -f makefile
+endif
+ifeq ($(TARGET_PLATFORM), PC)
+ifeq ($(TIDL_REF_AVX_FILE_EXISTS) , 1)
+	@echo .
+	@echo ======== MAKING TIDL REF AVX =================
+	$(MAKE) -C ./tidl_ref/source/avx -f makefile
+endif
 endif
 
-tidl_obj_clean:
-ifeq ($(TIDL_OBJ_ALGO_FILE_EXISTS) , 1)
+tidl_ref_clean:
+ifeq ($(TIDL_REF_FILE_EXISTS) , 1)
 	@echo .
-	@echo ======== MAKING TIDL OBJ ALGO =================
-	$(MAKE) -C ./ti_dl/algo/src -f makefile clean
+	@echo ======== CLEANING TIDL REF =================
+	$(MAKE) -C ./tidl_ref/source -f makefile clean
+endif
+ifeq ($(TARGET_PLATFORM), PC)
+ifeq ($(TIDL_REF_AVX_FILE_EXISTS) , 1)
+	@echo .
+	@echo ======== CLEANING TIDL REF AVX =================
+	$(MAKE) -C ./tidl_ref/source/avx -f makefile clean
+endif
 endif
 
-tidl_lib:tidl_algo tidl_priv tidl_obj custom
+tidl_kernels:
+ifeq ($(TIDL_KERNELS_FILE_EXISTS) , 1)
+	@echo .
+	@echo ======== MAKING TIDL KERNELS =================
+ifeq ($(TARGET_PLATFORM) , PC)
+	cmake -B ./tidl-kernels/x86_64_build ./tidl-kernels -DSOC=$(TARGET_SOC) -DBUILD_ALL_KERNELS=ON -DPSDK_INSTALL_PATH=$(PSDK_INSTALL_PATH) -DPERF_MODEL=1 -DBUILD_TESTS=OFF -DHOST_EMU=ON -DCMAKE_BUILD_TYPE=$(TARGET_BUILD) -DINSTALL_PATH=$(ALGBASE_PATH)/ti_dl -DTIDL_EXCLUDE_UNSUPPORTED_KERNELS=$(TIDL_EXCLUDE_UNSUPPORTED_KERNELS)
+	$(MAKE) -C ./tidl-kernels/x86_64_build -f Makefile install
+else
+	cmake -B ./tidl-kernels/dsp_build ./tidl-kernels -DSOC=$(TARGET_SOC) -DBUILD_ALL_KERNELS=ON -DPSDK_INSTALL_PATH=$(PSDK_INSTALL_PATH) -DBUILD_TESTS=OFF -DHOST_EMU=OFF -DCMAKE_BUILD_TYPE=$(TARGET_BUILD) -DINSTALL_PATH=$(ALGBASE_PATH)/ti_dl -DTIDL_EXCLUDE_UNSUPPORTED_KERNELS=$(TIDL_EXCLUDE_UNSUPPORTED_KERNELS)
+	$(MAKE) -C ./tidl-kernels/dsp_build -f Makefile install
+endif
+endif
+
+tidl_kernels_clean:
+ifeq ($(TIDL_KERNELS_FILE_EXISTS) , 1)
+	@echo .
+	@echo ======== CLEANING TIDL KERNELS =================
+ifeq ($(TARGET_PLATFORM) , PC)
+	@if [ -d "./tidl-kernels/x86_64_build" ]; then \
+		$(MAKE) -C ./tidl-kernels/x86_64_build -f Makefile clean; \
+		rm -rf ./tidl-kernels/x86_64_build; \
+	fi
+else
+	@if [ -d "./tidl-kernels/dsp_build" ]; then \
+		$(MAKE) -C ./tidl-kernels/dsp_build -f Makefile clean; \
+		rm -rf ./tidl-kernels/dsp_build; \
+	fi
+endif
+endif
+
+tidl_lib:tidl_algo tidl_priv tidl_ref custom tidl_kernels
 	@echo .
 	@echo ======== MAKING TIDL AND CUSTOM LIBRARIES =================
 
-tidl_lib_clean:tidl_algo_clean tidl_priv_clean tidl_obj_clean custom_clean
+tidl_lib_clean:tidl_algo_clean tidl_priv_clean tidl_ref_clean custom_clean tidl_kernels_clean
 	@echo .
 	@echo ======== CLEANING TIDL AND CUSTOM LIBRARIES =================
 
-tidl:custom tidl_lib
+tidl_tiovx_dsp_kernels:
+	@echo .
+	@echo ======== MAKING TIDL TIOVX DSP KERNELS =================
+	$(MAKE) -C ./tiovx_kernels -f makefile all
+
+tidl_tiovx_dsp_kernels_clean:
+	@echo .
+	@echo ======== CLEANING TIDL TIOVX DSP KERNELS =================
+	$(MAKE) -C ./tiovx_kernels -f makefile clean
+
+tidl: tidl_lib tidl_tiovx_dsp_kernels
 	@echo .
 	@echo ======== MAKING TIDL TEST =================
 	$(MAKE) -C ./ti_dl/test -f makefile final_install
 
-tidl_clean:custom_clean tidl_lib_clean
+tidl_clean: tidl_lib_clean tidl_tiovx_dsp_kernels_clean
 	@echo .
 	@echo ======== CLEANING TIDL TEST =================
 	$(MAKE) -C ./ti_dl/test -f makefile clean
@@ -261,14 +354,14 @@ tidl_rt_clean:
 
 nc:
 	@echo .
-ifeq ($(TIDL_NC_FILE_EXISTS) , 1)
-	@echo ======== MAKING NC =================
+ifeq ($(TIDL_PERFSIM_FILE_EXISTS) , 1)
+	@echo ======== MAKING TIDL PERFSIM =================
 	$(MAKE) -C ./ti_dl/utils/perfsim -f makefile
 endif
 nc_clean:
 	@echo .
-ifeq ($(TIDL_NC_FILE_EXISTS) , 1)
-	@echo ======== CLEANING NC ===============
+ifeq ($(TIDL_PERFSIM_FILE_EXISTS) , 1)
+	@echo ======== CLEANING TIDL PERFSIM ===============
 	$(MAKE) -C ./ti_dl/utils/perfsim -f makefile clean
 	cd ti_dl/utils/perfsim && $(RM_CMD) ti_cnnperfsim*
 endif
@@ -276,13 +369,13 @@ endif
 ms:
 	@echo .
 ifeq ($(TIDL_MS_FILE_EXISTS) , 1)
-	@echo ======== MAKING Model security =================
+	@echo ======== MAKING MODEL SECURITY =================
 	$(MAKE) -C ./ti_dl/utils/tidlModelSecure -f makefile
 endif
 ms_clean:
 	@echo .
 ifeq ($(TIDL_MS_FILE_EXISTS) , 1)
-	@echo ======== CLEANING Model security ===============
+	@echo ======== CLEANING MODEL SECURITY ===============
 	$(MAKE) -C ./ti_dl/utils/tidlModelSecure -f makefile clean
 	cd ti_dl/utils/tidlModelSecure && $(RM_CMD) tidl_model_secure*
 endif
@@ -413,9 +506,11 @@ scrub: cleanall
 	rm -rf ./arm-tidl/tiovx_kernels/lib
 	rm -rf ./ti_dl/utils/tidlModelImport/lib/
 	rm -rf ./ti_dl/utils/tidlModelImport/out/
-	rm -rf /ti_dl/utils/tidlModelSecure/out/
-	rm ./ti_dl/test/PC_dsp_test_dl_algo.out
-	rm ./ti_dl/test/j7-c71_0-fw
+	rm -rf ./ti_dl/utils/tidlModelSecure/out/
+	rm -rf ./tiovx_kernels/lib
+	rm -rf ./tiovx_kernels/out
+	rm -f ./ti_dl/test/PC_dsp_test_dl_algo.out
+	rm -f ./ti_dl/test/j7-c71_0-fw
 
 it_run:
 	cd ti_dl/utils/tidlModelImport && $(IT_RUN_SCRIP) &&  cd ../../../
@@ -435,18 +530,53 @@ run: it_run tidl_run
 dss_run:
 	cd ti_dl/utils/targetTest && C:\ti\ccs910\ccs\ccs_base\scripting\bin\dss.bat launch_tidl_v2.js
 
-tidl_tiovx_kernels:
+tidl_tiovx_arm_kernels:
 	@echo .
-	@echo ======== MAKING TIDL TIOVX KERNELS =================
-	$(MAKE) -C ./arm-tidl/tiovx_kernels -f makefile all
+	@echo ======== MAKING TIDL TIOVX ARM KERNELS =================
+	$(MAKE) -C ./arm-tidl -f makefile tidl_tiovx_arm_kernels
 
-tidl_tiovx_kernels_clean:
+tidl_tiovx_arm_kernels_clean:
 	@echo .
-	@echo ======== CLEANING TIDL TIOVX KERNELS =================
-	$(MAKE) -C ./arm-tidl/tiovx_kernels -f makefile clean
+	@echo ======== CLEANING TIDL TIOVX ARM KERNELS =================
+	$(MAKE) -C ./arm-tidl -f makefile tidl_tiovx_arm_kernels_clean
 
-.PHONY: nc it tidl ms nc_clean it_clean tidl_clean ms_clean it_clean protos_clean protos  it_run tidl_run gv gv_clean gv_rt gv_rt_clean dt dt_clean tidl_tiovx_kernels tidl_tiovx_kernels_clean scrub
+install:
+ifndef TIDL_PATH
+	$(error TIDL_PATH is not defined. Please set TIDL_PATH before running install)
+else
+	@echo "Installing to $(TIDL_PATH)...";
+	@if [ -d "$(TIDL_PATH)" ]; then \
+		mkdir -p $(TIDL_PATH)/ti_dl/lib/; \
+		mkdir -p $(TIDL_PATH)/ti_dl/inc/; \
+		mkdir -p $(TIDL_PATH)/tiovx_kernels/lib/; \
+		cp -rfL ./ti_dl/lib/* $(TIDL_PATH)/ti_dl/lib/ 2>/dev/null || :; \
+		cp -rfL ./ti_dl/inc/* $(TIDL_PATH)/ti_dl/inc/ 2>/dev/null || :; \
+		cp -rfL ./tiovx_kernels/lib/* $(TIDL_PATH)/tiovx_kernels/lib/ 2>/dev/null || :; \
+		echo "TIDL Libraries and Headers Installation complete"; \
+	else \
+		echo "Error: TIDL_PATH '$(TIDL_PATH)' does not exist. Please provide a valid directory path."; \
+		exit 1; \
+	fi
+endif
 
+install_tidl_tools:
+ifeq ($(TARGET_PLATFORM), PC)
+	@echo "Copying tidl_tools tarball to $(TIDL_PATH)/tidl_tools/$(TARGET_SOC)...";
+	@if [ ! -d "$(TIDL_PATH)" ]; then \
+		echo "Error: TIDL_PATH '$(TIDL_PATH)' does not exist. Please provide a valid directory path."; \
+		exit 1; \
+	fi
+
+	@if [ ! -d "./tidl_tools" ]; then \
+		echo "Error: tidl_tools directory does not exist."; \
+		exit 1; \
+	fi
+	@mkdir -p $(TIDL_PATH)/tidl_tools/$(TARGET_SOC);
+	@tar -h -czf $(TIDL_PATH)/tidl_tools/$(TARGET_SOC)/tidl_tools.tar.gz -C ./tidl_tools .;
+	@echo "TIDL_TOOLS Installation complete";
+endif
+
+.PHONY: nc it tidl ms nc_clean it_clean tidl_clean ms_clean it_clean protos_clean protos it_run tidl_run gv gv_clean gv_rt gv_rt_clean dt dt_clean tidl_tiovx_arm_kernels tidl_tiovx_dsp_kernels tidl_tiovx_arm_kernels_clean tidl_tiovx_dsp_kernels_clean scrub tidl_lib tidl_lib_clean tidl_algo tidl_algo_clean tidl_priv tidl_priv_clean tidl_ref tidl_ref_clean tidl_kernels tidl_kernels_clean custom custom_clean install install_tidl_tools
 
 
 
